name = "sohan-light-cards"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/SohanChy/blog/master/LICENSE"
description = "sohan-light-cards is a card based simple light blog theme for hugo."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Sohan Chowdhury"
    homepage = "http://sohanchy.com/"
