name = "Robust"
license = "MIT"
licenselink = "https://github.com/dim0627/hugo_theme_robust/blob/master/LICENSE.md"
description = "Robust is blog theme for hugo."
tags = ["blog"]
features = ["blog"]
min_version = 0.15

[author]
    name = "Daisuke Tsuji"
    homepage = "http://yet.unresolved.xyz/"

